### PR TITLE
Changed &$this to $this

### PR DESCRIPTION
**Pull request by davidshq**

### CODE REVIEW

**Comment by stevengliebe** [comment]
Thanks David. Do you want to revise this to not modify the ct-plugin-settings and ct-meta-box subdules? Feel free to submit separate pull requests for those two projects.

**Comment by davidshq** [comment]
Sure. I think I did, let me know if it didn't work.

**Comment by stevengliebe** [comment]
Thanks, that looks good. I'll merge it into the next release.

**Comment by stevengliebe** [comment]
Thanks David, will release a small update to CTC today.

**Pull request merged**
