### PR TITLE
Add video enclosure for podcast feed

### PR DESCRIPTION
**Pull request by mintplugins**
This PR adds video enclosure support for podcasting, if a valid video URL has been set.

### CODE REVIEW

**Comment by stevengliebe** [comment]
Hey Phil, this is not in my plans for CC/CCP so I think your best bet might be to run your code on the `ctc_correct_sermon` or `ctc_after_save_sermon` action right after `ctc_do_enclose` is triggered.

**Comment by mintplugins** [comment]
Hey Steven, 

Thanks for the response. I'll look at doing that. Any reason this isn't part of your plans?

**Comment by stevengliebe** [comment]
Demand for video podcasting has been nearly zero and I'm turning my attention towards [WP Sermons](https://wpsermons.com) as far as sermon features go.

**Comment by mintplugins** [comment]
@stevengliebe I have had requests for it, and since the PR is done and works, is there any reason not to merge it aside from it being icing in that other (competing?) plugin? I don't see it being a maintenance burden as its pretty simple, and since videos are an option built into this plugin, it makes sense they would work just like audio files.

**Comment by mintplugins** [comment]
That being said, if you do see this as a big maintenance burden for a reason I haven't considered, I definitely respect your decision. I just want to understand why its being denied more fully.

**Comment by stevengliebe** [comment]
I'd need to spend time looking into the implications (I believe there may be several) but don't have time. With WP Sermons coming, advancing CC is not a priority (maintaining it indefinitely is). I think you should be accomplish what you want with hooks.

**Pull request closed without merging**
