### PR TITLE
added event registration meta box and registration URL setting

### PR DESCRIPTION
**Pull request by galengidman**

### CODE REVIEW

**Comment by stevengliebe** [comment]
Thanks, Galen! Looks good. I plan on merging this next time I sit down to work on the plugin.

**Comment by stevengliebe** [comment]
I'm still planning on incorporating this. I've been clearing out some maintenance type things first (with the last couple updates).

**Comment by galengidman** [comment]
Sounds good Steven, whenever you get to it.

**Comment by stevengliebe** [comment]
This is done and pushed to GitHub. Will release on WordPress.org shortly. Thank you!

**Comment by galengidman** [comment]
Make sure to update https://github.com/churchthemes/church-theme-content/blob/master/includes/admin/admin-event-fields.php#L525 to reflect version 1.6 instead of 1.5.

**Comment by galengidman** [comment]
And thanks! Glad to contribute to this project in a small way!

**Comment by stevengliebe** [comment]
Oh, thanks for catching that. Will fix it in the next update.

**Pull request merged**
